### PR TITLE
Fix casting strings to bools

### PR DESCRIPTION
**Pull request by gabriel403**
Casting "false" to bool is always true, use filter_var instead

### CODE REVIEW

**Comment by gabriel403** [comment]
With these changes we go from 

```
Draft / 0, Editing / 1729, Preview / 100, Approved / 0, Published /
3415, Excluded / 0, Offlined / 0, Archived / 0
```

to

```
Draft / 0, Editing / 2864, Preview / 49, Approved / 0, Published / 2331, Excluded / 0, Offlined / 0, Archived / 0
```

Which matches the original code

**Comment by gabriel403** [comment]
Tests fixed

**Comment by weshooper** [comment]
:+1:

**Comment by ziadoz** [comment]
:+1:

**Pull request merged**
